### ISSUE TITLE
Parse makernotes.

### ISSUE THREAD

**Issue by srivathsanmurali** [srivathsanmurali/exif_parser#1]
# TODO
+ [ ] Create a behaviour/protocol to implement maker_note parsing.
+ [ ] Add option to provide parser.
+ [ ] Implement common formats inside the library.
  - [ ] Cannon
  - [ ] Nikon
